name: Lint markdown
"on":
  push:
    branches:
      - main
      - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DavidAnson/markdownlint-cli2-action@v11
        with:
          fix: true
          config: ".markdownlint.jsonc"
          globs: "**/*.md"
